
The following have been reloaded with a version change:
  1) Mambaforge/23.3.1-fasrc01 => Mambaforge/22.11.1-fasrc01
  2) python/3.10.12-fasrc01 => python/3.10.9-fasrc01

Traceback (most recent call last):
  File "/n/home06/mbritt/VAFQMC/importancevafqmc/pes.py", line 30, in <module>
    run_simulation(dist)
  File "/n/home06/mbritt/VAFQMC/importancevafqmc/pes.py", line 25, in run_simulation
    opt_params = prop.run()
                 ^^^^^^^^^^
  File "/n/home06/mbritt/VAFQMC/importancevafqmc/hmc_vafqmc_lbfgs.py", line 347, in run
    h1e, v2e, nuc, l_tensor = self.hamiltonian_integral()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home06/mbritt/VAFQMC/importancevafqmc/hmc_vafqmc_lbfgs.py", line 121, in hamiltonian_integral
    fa["h1e"] = h1e
    ~~^^^^^^^
  File "/n/home06/mbritt/.conda/envs/afqmc_env/lib/python3.12/site-packages/h5py/_hl/group.py", line 484, in __setitem__
    h5o.link(ds.id, self.id, name, lcpl=lcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 253, in h5py.h5o.link
OSError: Unable to create link (name already exists)
